---
title: "Tableau Story: Writeup"
author: "Ekaterina Kravtchenko"
date: "8/15/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Materials

* [**Final visualization**](https://public.tableau.com/views/PISA_wealth_final/TheRelationshipBetweenSocio-EconomicWell-BeingandPISATestPerformance?:embed=y&:display_count=yes&publish=yes)
* [**Initial visualization**](https://public.tableau.com/shared/6G4FQZ4J8?:display_count=yes)
* [**Codebook**](./codebook.html)
* **Data files** used for final visualization: [subregion_data.csv](./subregion_data.csv), [country_data.csv](./country_data.csv)
* **Feedback**: [feedback.m4a](./feedback.m4a)

## Summary

My project focuses on the 2012 PISA dataset.  In my visualization, I show that various factors connected to individual and region-wide socio-economic well-being are predictive of international and regional math, reading, and science test scores.  

## Design

I wanted to plot these primary trends:

* **Test results by country**: this is likely most easily visualized using a map, with test results color-coded.  To avoid use of multiple maps, I made one map, and an interactive parameter which allows users to select the test result they want to see.
* **Relationship of scores with SES (socio-economic status)**: I chose several obvious quantitative measures of family socio-economic status: family wealth; family social, economic, and cultural status; and parents' years of education.  I also calculated one regional measure of socio-economic well-being, after noticing that it more consistently predicted the success of the highest-scoring countries: wealth inequality.  Wealth inequality plausibly influences regional test scores, as it may ensure that access to good schooling is not determined by relative family wealth, and that all students receive equally adequate (or, perhaps, equally inadequate) schooling.
* **Highest-scoring countries/country rank**: The relative rank of countries is more difficult to spot using a map.  For this purpose, I created a bar plot which allows users to sort and select results.  Again, to avoid the creating of multiple plots, I allow users to select which test subject to plot (this is not critical, however, as test scores are clearly highly correlated).  Since I want the user to see a pattern in multiple measures, however, I do create separate plots for all these measures - otherwise, too much effort is required on the user's part to find all the information I want them to see.
* **Relationship between country rank and SES (socio-economic status)**: The clearest and most economical way to communicate this relationship that I could think of was to color the country bars according to how 'well' they scored on various (scaled) measures of socio-economic status.  I selected an orange/red to blue scale, as this seems most easily interpreted as ranging from 'poor' to 'good.'  This makes it relatively easy to see, for example, if all high-scoring countries also 'score' well on socio-economic measures (or if low-scoring countries 'score' poorly).  The use and purpose of color is briefly explained.
* **Correlation between scores and SES**: As country data is relatively sparse, I plot the correlations between group scores and socio-economic measures at the subregional level, where there data is abundant.  This also makes it more likely that countries where data is very sparse, and perhaps only collected from a single region, will not unduly influence the apparent relationship between measures.  Further, if the same patterns seen at the international level are replicated at the subregional level, it strengthens the hypothesis of a relationship between the relevant variables.  The points are tentatively color-coded for consistency, and to make it easier for the user to visually examine the strength of the relationship between SES measures and test scores in the case of either 'good' or 'bad' values.
* **Overall story**: Space permitting, the user is guided explicitly through the visualizations, and the major patterns they are expected to spot are explicitly pointed out.

After collecting feedback, I made the graphic somewhat less free-form and interactive.  It became clear that simply setting up the scenario, including clues to guide the user in gaining their own insights, did not effectively get the intended point across.  In the end, I decided to focus on a relatively limited phenomenon (I had originally planned to add more unrelated measures that the user could dynamically plot, if they wanted), clearly spell out intended conclusions, present all critical plots instead of expecting the user to dynamically generate them, and provide a more clear guide to interpreting use of color.  I also changed the color schemes to something (hopefully) more easily interpretable (in terms of a consistent gradient from 'good' to 'bad').

## Feedback

The feedback I got was the following, summarized:

* Insights to be gained were completely opaque - the user was able to compare country performance, but did not get the link between socio-economic factors and test scores at all.
* Use of color was confusing and poorly explained - the user was unable to tell if a color signified something 'good,' something 'bad,' or nothing at all - or which patterns they were supposed to spot.
* Map moved around too much and was somewhat difficult to work with/zoom (this seems to be a flaw inherent to Tableau, however).
* It was unclear what, in fact, was being plotted.  To some degree, the plots alone seem insufficient to explain what the PISA is, but this could nevertheless be made clearer.

## Resources

The resources I used are the following:

* PISA 2012 [technical report](./PISA-2012-technical-report-final.pdf), and [results overview](./pisa-2012-results-overview.pdf), for interpreting results and comparing generated country test scores.
* [`intsvy`](https://www.jstatsoft.org/article/view/v081i07/0) R package for generating country-wide and regional test scores, as the PISA guides indicate individual student scores are not informative (https://nces.ed.gov/surveys/pisa/faq.asp#10).
* Info on calculating Gini coefficient (measure of wealth inequality): https://en.wikipedia.org/wiki/Gini_coefficient